name: express.js

on:
  push:
    branches: [ "master" ]
  schedule:
    #- cron: '0 12 * * *'
    - cron: '15 17 * * *' #调试

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 12.x
      uses: actions/setup-node@v3
      with:
        node-version: 12.x
        cache: 'npm'
    - run: npm i
    - run: npm start
